### PR TITLE
Added 'id' as a writable attributes as specified in Google V3 API, with format validation

### PR DESCRIPTION
**Pull request by tomav**
Now ID can be specified when you create an event as talked here https://github.com/northworld/google_calendar/issues/61 
I currently don't have a ruby environment to launch the tests, let's see what travis says.

### CODE REVIEW

**Comment by tomav** [comment]
Just seen Travis feedback, I'll have a look.
@szich, do not hesitate if you have any suggestion.

**Comment by szich** [comment]
Looks good, thanks!

**Comment by tomav** [comment]
Hmm, I think my 2 PRs are in fact the same one...
How can we see the merge conflict?

**Comment by tomav** [comment]
@szich tell me how I can help.

**Comment by szich** [comment]
@tomav thanks for the offer to help.  I think I manually merged the changes properly.  If not let me know.

**Comment by tomav** [comment]
Seems to be Ok.
And last question: how frequent are gem updates? (I don't use a Gemfile on my project)

**Comment by szich** [comment]
It depends on the number of pull requests we receive.  We're going to push a new version soon.

**Pull request closed without merging**
