### PR TITLE
parse_options now accepts text query (q) param

### PR DESCRIPTION
**Pull request by talyaniv**
Hi Guys, great job with this gem!

I needed to add a textual query to find_future_events so I could quickly find all future events with some keyword. I ended up adding an optional 'q' param to parse_options, so that every method that uses it can now add 'q' to the options.

I added a test for it.

### CODE REVIEW

**Comment by szich** [comment]
It looks like you inadvertently broke the build.  Once the build is passing I will gladly merge your pull request.

**Comment by talyaniv** [comment]
Now builds correctly. In addition to the logic, I did some minor readability change, see
lib/google/calendar.rb:346~355
I broke the previous long concatenated string into code chunks for better readability.

**Comment by szich** [comment]
Thanks for improving the code!

**Comment by talyaniv** [comment]
Cool! happy to contribute, keep the good work going!

**Pull request merged**
