### PR TITLE
use JSON.generate instead of string concatenation

### PR DESCRIPTION
**Pull request by rxbynerd**
We've seen numerous problems with this library due to the way it generates JSON - primarily, a newline is present in the description when we fetch it, it chokes when we come to update it.

I've updated this library to use ```JSON.generate``` instead, which should properly format newlines and other UTF-8 characters like emoji correctly, and ensured the tests pass locally.

### CODE REVIEW

**Comment by szich** [comment]
@rxbynerd Thank you so much for taking this on, it is LONG overdue. 👏 

There are a two changes needed before I can merge it.  The main one is the helper methods used to generate an event's json now return a hash (recurrence_json and similar).  This will break code for people who are currently using those methods and expecting them to return json.

The other issue is a typo in the color_json method, the attribute name is quoted, so the value is never returned.

I really like the way you cleaned up the extended_properties_json routine, nice job!

**Comment by rxbynerd** [comment]
* ah! sorry about ```color_json``` - that'll teach me to double-check PRs before I submit!
* r.e. ```recurrence_json``` - that's a thorny one, and I did feel pretty gross returning ```Hash```'s from those methods anyway. How do you feel about moving the current implementations across to ```$x_attributes``` (```recurrence_attributes```, ```colour_attributes```, etc), then making single-line methods to generate JSON from those attribute methods? Meaning we can easily expose either ```Hash``` or ```JSON``` with one implementation, but at the cost of a few more methods?

**Comment by szich** [comment]
That sounds like a nice solution, go for it.

**Comment by szich** [comment]
@rxbynerd there are conflicts that need to addressed before I can merge this.

**Comment by edwinwills** [comment]
Hi @szich - I've rebased against master and added the `attributes`_ methods that @rxbynerd suggested as well.

**Comment by szich** [comment]
Looks great, thanks!

**Pull request merged**
